export default {
  BENEFICIARY: "/beneficiary",
  BASIC_INFO: "/basic-info",
  EDUCATION_INFO: "/education-info",
  FINANCIAL: "/financial-info",
  OTHER_INFO: "/identification",
  HEALTH_INFO: "/health-info",
  ASSET_INFO: "/asset-ownership",
  ACCESS_INFO: "/access-to-service",
  SELF_DECLARATION: "/consent",
  UPDATE_COWIN_ID: "/update-cowin-id",
  BENEFICIARY_OVERVIEW: "/overview",
  BENEFICIARY_ID_PROOF: "/id-proof-collection",
  SCHEDULE_APPOINTMENTS: "/schedule-appointment",
  APPOINTMENT_DETAILS: "/appointment-details",
  APPOINTMENT_PDF: "/view-appointment-pdf",
  BENEFICIARY_LIST: "/beneficiary-list",
  VIAL_NUMBER: "/vial-number",
  ORGANISATION: "/organisation",
  OVERVIEW: "/overview",
  LEADERSHIP: "/leadership",
  LOCATION: "/location",
  PURPOSE: "/purpose",
  TRACK_RECORDS: "/track-record",
  ORG_BENEFICIARIES: "/beneficiaries",
  DOCUMENTS: "/documents",
  LEGAL: "/legal",
  ORG_PREVIEW: "/preview",
  SO_SUBMIT: "/soSubmit",
  MILESTONE:"/mileStone",
  REPORTING:"/reporting",
  PROPOSAL_SUMMARY:"/proposal",
  TASK_MANAGER:"/task_manager",
  PROGRAM_CREATION: "/program-creation",
  PROGRAM_OVERVIEW: "/program-overview",
  PROGRAM_OVERVIEW_MAIN: "/program-overview",
  PROGRAM_PREVIEW: "/preview-project",
  PRG_IMPACT_CATEGORY: "/impact-category",
  PRG_IMPACT_PRIORITIES: "/impact-priorities",
  PRG_STRATEGIC_GOALS: "/strategic-goals",
  PRG_PROGRAM_NAME: "/choose-program-name",
  PRG_BASIC: "/basic-details",
  PRG_TEAM: "/team-details",
  PRG_METRICS: "/metrics",
  PRG_BUDGET: "/budget",
  PRG_DONOR: "/donor",
  PRG_REPORTING: "/reporting",
  PRG_ORGANIZATIONAL_APPROVAL: "/organisational-approval",
  PRG_VALIDATOR: "validator",
  AGREEMENT: "/agreement",
  VALIDATOR:"/validator",
  PROPOSALS:"/proposals",
  ORGANISATIONS:"/organisations",
  VALIDATOR_DASHBOARD:'/dashboard',
  VALIDATOR_REGISTRATION: '/registration',
  VALIDATOR_DOCUMENTS: '/documents',
  IMPLEMENTATION_PARTNERS: '/implementation-partners',
  PROGRAMS: '/programs'
};
