export const PROJECT = {
  UMEEED: "Ummeed",
  ARPAN: "Arpan",
};

export const PROGRAM_STATUS = {
  ACTIVE: "ACTIVE",
  DRAFT: "DRAFT",
  ACHIEVED: "ACHIEVED",
};

export const METRICS = {
  CATEGORY: "CATEGORY",
  PRIORITY: "PRIORITY",
  STRATEGIC_GOALS: "STRATEGIC_GOALS",

  CHANGE_CATGORY: "CHANGE_CATGORY",
  CHANGE_PRIORITY: "CHANGE_PRIORITY",
  CHANGE_GOALS: "CHANGE_GOALS",
};

export const ROLES = {
  FIELD_AGENT: "FIELD-AGENT",
  SOCIAL_ADMIN: "SOCIAL-ADMIN",
  HEALTH_WORKER: "HEALTH-WORKER",
  VALIDATOR: "VALIDATOR",
  ADMIN: "ADMIN",
};

export const STATUS = {
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
};
